version = 3

[upgrade]
source = "cdn"
interval = "168h"
auto = false
notice = false

[[blocks]]
type = "rprompt"
overflow = "hidden"

  [[blocks.segments]]
  type = "executiontime"
  style = "plain"
  foreground = "yellow"
  background = "transparent"
  template = "{{ .FormattedMs }}"

    [blocks.segments.properties]
    threshold = 5_000

[[blocks]]
type = "prompt"
alignment = "left"

  [[blocks.segments]]
  type = "path"
  style = "plain"
  background = "transparent"
  foreground_templates = [
  "{{if gt .Code 0}}red{{end}}",
  "{{if eq .Code 0}}white{{end}}"
]
  template = "["

  [[blocks.segments]]
  type = "path"
  style = "plain"
  background = "transparent"
  foreground = "blue"
  template = "{{ .Path }}"

    [blocks.segments.properties]
    style = "folder"

  [[blocks.segments]]
  type = "git"
  style = "plain"
  background = "transparent"
  foreground = "white"
  template = " | "

  [[blocks.segments]]
  type = "git"
  style = "plain"
  foreground = "#6c6c6c"
  background = "transparent"
  template = "{{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }}<cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡ {{ end }}</>"

    [blocks.segments.properties]
    branch_icon = ""
    commit_icon = "@"
    fetch_status = true

  [[blocks.segments]]
  type = "python"
  style = "plain"
  background = "transparent"
  foreground = "white"
  template = " | "

    [blocks.segments.properties]
    display_mode = "environment"
    fetch_virtual_env = true
    home_enabled = true

  [[blocks.segments]]
  type = "python"
  style = "plain"
  background = "transparent"
  foreground = "yellow"
  powerline_symbol = ""
  template = " {{ if .Venv }} {{ .Venv }}{{ end }}"

    [blocks.segments.properties]
    display_mode = "environment"
    fetch_virtual_env = true
    home_enabled = true

  [[blocks.segments]]
  type = "path"
  style = "plain"
  background = "transparent"
  foreground_templates = [
  "{{if gt .Code 0}}red{{end}}",
  "{{if eq .Code 0}}white{{end}}"
]
  template = "] "

[transient_prompt]
background = "transparent"
foreground_templates = [
  "{{if gt .Code 0}}red{{end}}",
  "{{if eq .Code 0}}white{{end}}"
]
template = "[] "

[secondary_prompt]
foreground = "white"
background = "transparent"
template = "↪ "

